# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15QZ4Wpb-FuTGGvM71piYhPOhH94tcZtO
"""

def Calc(num1, num2, operator):
    if operator == '+':
      return num1 + num2
    elif operator == '-':
      return num1 - num2
    elif operator == '*':
      return num1 * num2
    elif operator == '/':
      if num2 == 0:
        return 'Zero Division Error'
      else:
        return num1 / num2
    else:
      return 'Invalid Operator'

num1=float(input('Enter first number: '))
num2=float(input('Enter second number: '))
operator=input('Enter operator(+,-,*,/): ')
print(Calc(num1, num2, operator))