# -*- coding: utf-8 -*-
"""Calc_expenses.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EL5zMTtMW-tBEdraEqE51g14wmHpWNZc
"""

def calculate_total_expenses(filename):
    """
    Reads the expenses from the specified file and calculates the total amount spent.

    :param filename: Name of the file to read from.
    :return: The total amount spent.
    """
    total = 0.0

    try:
        with open(filename, 'r') as file:
            for line in file:
                # Extract the amount from the line
                if ':' in line:
                    try:
                        # Split the line into description and amount
                        description, amount_str = line.split(':', 1)
                        # Convert the amount to a float (remove any non-numeric characters like 'Rs')
                        amount = float(amount_str.strip().replace('Rs', '').replace(',', ''))
                        total += amount
                    except ValueError:
                        print(f"Warning: Could not parse line: {line.strip()}")

    except FileNotFoundError:
        print(f"The file {filename} does not exist.")
    except IOError:
        print(f"An error occurred while reading the file {filename}.")

    return total

def main():
    filename = 'expenses.txt'
    total = calculate_total_expenses(filename)
    print(f"Total amount spent: ${total:.2f}")

if __name__ == "__main__":
    main()