# -*- coding: utf-8 -*-
"""constant.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANbb9aOO7dnY9L2P_uTm0TrPxIVlMORz
"""

pi=3.142

speed_of_light=3*10e8

