# -*- coding: utf-8 -*-
"""count_words.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZ_vkwJb6I_C0M7lL85XnZJo9pmooLxX
"""

import string
from collections import Counter

def count_words(filename):
    """
    Reads the text from the specified file and counts the occurrences of each word.

    :param filename: Name of the file to read from.
    :return: A dictionary with words as keys and their counts as values.
    """
    word_count = Counter()

    try:
        with open(filename, 'r') as file:
            text = file.read()

            # Convert text to lowercase and remove punctuation
            text = text.lower()
            text = text.translate(str.maketrans('', '', string.punctuation))

            # Split the text into words
            words = text.split()

            # Count occurrences of each word
            word_count.update(words)

    except FileNotFoundError:
        print(f"The file {filename} does not exist.")
    except IOError:
        print(f"An error occurred while reading the file {filename}.")

    return word_count

def main():
    filename = 'paragraph.txt'
    word_count = count_words(filename)

    # Sort the words alphabetically and print the counts
    for word in sorted(word_count.keys()):
        print(f"{word}: {word_count[word]}")

if __name__ == "__main__":
    main()