# -*- coding: utf-8 -*-
"""file_operation_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntrqf4M_1ki6OYqvWd1sRd5lLCWTSol9
"""

def read_file(filepath):
  try:
    with open(filepath, 'r') as f:
      lines = f.read()
    return lines
  except FileNotFoundError:
    print(f'File {filepath} not found')
    return None
def write_file(filepath, content):
  with open(filepath, 'w') as f:
    f.write(content)
    print("Content written to file succesfully")
def append_file(filepath, content):
  with open(filepath, 'a') as f:
    f.write(content)
    print("Content appended to file succesfully")