# -*- coding: utf-8 -*-
"""read_inventory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0EZNLOZXL5mmJolkTE939zs6KxumXRN
"""

def read_and_display_file(filename):
    """
    Opens the specified file in read mode and displays its contents line by line.

    :param filename: Name of the file to read from.
    """
    try:
        # Open the file in read mode
        with open(filename, 'r') as file:
            # Iterate over each line in the file
            for line in file:
                # Print the line (removing trailing newlines)
                print(line.strip())
    except FileNotFoundError:
        print(f"The file {filename} does not exist.")
    except IOError:
        print(f"An error occurred while reading the file {filename}.")

def main():
    filename = 'inventory.txt'
    read_and_display_file(filename)

if __name__ == "__main__":
    main()