# -*- coding: utf-8 -*-
"""String_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOC6jFEVJswTbBLKLx0WMdLIgpRJZBOC
"""

def string_manipulation(st):
  def string_rev(st):
    if type(st)==str:
      print(f" The reversed string is: {st[::-1]}")
    else:
      print("Invalid Input")
  def string_cap(st):
    if type(st)==str:
      print(f" The capitalized string is: {st.upper()}")
    else:
      print("Invalid Input")

  string_rev(st)
  string_cap(st)

st=input("Enter a string: ")
string_manipulation(st)

